"""Rebuild the master index in readme.md and per-folder _index.md files.

Walks every cheat sheet, reads frontmatter, and rewrites the status table
in readme.md plus a flat table-of-contents per domain folder.
"""
from __future__ import annotations

import re
from collections import defaultdict
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
TOP_LEVEL_DOCS = {"readme.md", "template.md", "taxonomy.md", "contributing.md"}
FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n", re.DOTALL)
STATUS_TABLE_RE = re.compile(
    r"(\| Area\s+\| Sheets \| Notebooks \|\n\|[-:\| ]+\|\n)(?:\|.*\n)+",
)


def iter_sheets() -> list[Path]:
    sheets = []
    for p in ROOT.rglob("*.md"):
        if any(part.startswith("_") or part.startswith(".") for part in p.relative_to(ROOT).parts):
            continue
        if p.name in TOP_LEVEL_DOCS and p.parent == ROOT:
            continue
        sheets.append(p)
    return sheets


def parse_frontmatter(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    m = FRONTMATTER_RE.match(text)
    return yaml.safe_load(m.group(1)) if m else {}


def main() -> None:
    sheets = iter_sheets()
    by_domain: dict[str, list[tuple[Path, dict]]] = defaultdict(list)
    for s in sheets:
        fm = parse_frontmatter(s)
        domain = fm.get("domain", s.parent.relative_to(ROOT).as_posix())
        by_domain[domain].append((s, fm))

    # --- Rewrite readme.md status table ---
    readme = ROOT / "readme.md"
    text = readme.read_text(encoding="utf-8")
    rows = []
    for domain in sorted(by_domain):
        entries = by_domain[domain]
        n_sheets = len(entries)
        n_nb = sum(1 for _, fm in entries if fm.get("notebook"))
        rows.append(f"| {domain:<30} | {n_sheets:>6} | {n_nb:>9} |")
    new_table = (
        "| Area                           | Sheets | Notebooks |\n"
        "| ------------------------------ | -----: | --------: |\n"
        + "\n".join(rows)
        + "\n"
    )
    if STATUS_TABLE_RE.search(text):
        text = STATUS_TABLE_RE.sub(new_table, text, count=1)
        readme.write_text(text, encoding="utf-8")
        print(f"Updated readme.md status table ({len(rows)} domains).")
    else:
        print("WARNING: status table marker not found in readme.md")

    # --- Write per-domain _index.md ---
    for domain, entries in by_domain.items():
        folder = ROOT / domain
        if not folder.exists():
            continue
        lines = [
            f"# {domain}",
            "",
            "_Auto-generated by `_meta/scripts/build_index.py`. Do not edit by hand._",
            "",
            "| Sheet | Difficulty | Status | Notebook |",
            "| ----- | ---------: | ------ | -------- |",
        ]
        for sheet, fm in sorted(entries, key=lambda x: x[0].name):
            title = fm.get("title", sheet.stem)
            diff = fm.get("difficulty", "—")
            status = fm.get("status", "—")
            nb = f"[ipynb]({fm['notebook']})" if fm.get("notebook") else "—"
            lines.append(f"| [{title}]({sheet.name}) | {diff} | {status} | {nb} |")
        (folder / "_index.md").write_text("\n".join(lines) + "\n", encoding="utf-8")

    total_sheets = sum(len(v) for v in by_domain.values())
    total_nb = sum(1 for v in by_domain.values() for _, fm in v if fm.get("notebook"))
    print(f"Indexed {total_sheets} sheets, {total_nb} notebooks across {len(by_domain)} domains.")


if __name__ == "__main__":
    main()
